export const universities = [
  { value: "0", label: "Üniversiteniz" },
  { value: "245", label: "Abant İzzet Baysal Üniversitesi" },
  { value: "428", label: "Abdullah Gül Üniversitesi" },
  { value: "246", label: "Acıbadem Mehmet Ali Aydınlar Üniversitesi" },
  { value: "296", label: "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi" },
  { value: "247", label: "Adıyaman Üniversitesi" },
  { value: "249", label: "Afyon Kocatepe Üniversitesi" },
  { value: "453", label: "Afyonkarahisar Sağlık Bilimleri Üniversitesi" },
  { value: "250", label: "Ağrı İbrahim Çeçen Üniversitesi" },
  { value: "454", label: "Akdeniz Karpaz Üniversitesi" },
  { value: "252", label: "Akdeniz Üniversitesi" },
  { value: "253", label: "Aksaray Üniversitesi" },
  { value: "433", label: "Alanya Alaattin Keykubat Üniversitesi" },
  { value: "304", label: "Alanya Hamdullah Emin Paşa Üniversitesi" },
  { value: "322", label: "Altınbaş (Kemerburgaz) Üniversitesi" },
  { value: "254", label: "Amasya Üniversitesi" },
  { value: "255", label: "Anadolu Bil Meslek Yüksekokulu" },
  { value: "256", label: "Anadolu Üniversitesi" },
  { value: "257", label: "Anadolu Üniversitesi Açıköğretim Fakültesi" },
  { value: "352", label: "Anka Teknoloji Üniversitesi" },
  { value: "484", label: "Ankara Bilim Üniversitesi" },
  { value: "434", label: "Ankara Güzel Sanatlar Üniversitesi" },
  { value: "455", label: "Ankara Hacı Bayram Veli Üniversitesi" },
  { value: "456", label: "Ankara Medipol Universitesi" },
  { value: "457", label: "Ankara Müzik ve Güzel Sanatlar Üniversitesi" },
  { value: "435", label: "Ankara Sosyal Bilimler Üniversitesi" },
  { value: "258", label: "Ankara Türk Hava Kurumu Üniversitesi" },
  { value: "259", label: "Ankara Üniversitesi" },
  { value: "395", label: "Ankara Yıldırım Beyazıt Üniversitesi" },
  { value: "436", label: "Antalya Akev Üniversitesi" },
  { value: "437", label: "Antalya Bilim Üniversitesi" },
  { value: "260", label: "Ardahan Üniversitesi" },
  { value: "262", label: "Artvin Çoruh Üniversitesi" },
  { value: "263", label: "Atatürk Üniversitesi" },
  { value: "264", label: "Atılım Üniversitesi" },
  { value: "416", label: "Avrasya Üniversitesi" },
  { value: "248", label: "Aydın Adnan Menderes Üniversitesi" },
  { value: "265", label: "Bahçeşehir Üniversitesi" },
  { value: "266", label: "Balıkesir Üniversitesi" },
  { value: "438", label: "Bandırma Onyedi Eylül Üniversitesi" },
  { value: "267", label: "Bartın Üniversitesi" },
  { value: "268", label: "Başkent Üniversitesi" },
  { value: "269", label: "Batman Üniversitesi" },
  { value: "270", label: "Bayburt Üniversitesi" },
  { value: "481", label: "Belirsiz DRH Data" },
  { value: "480", label: "Belirsiz Üniversite" },
  { value: "272", label: "Beykent Üniversitesi" },
  { value: "273", label: "Beykoz Teknoloji Üniversitesi" },
  { value: "410", label: "Bezmialem Vakıf Üniversitesi" },
  { value: "274", label: "Bilecik Şeyh Edebali Üniversitesi" },
  { value: "276", label: "Bingöl Üniversitesi" },
  { value: "426", label: "Biruni Üniversitesi" },
  { value: "277", label: "Bitlis Eren Üniversitesi" },
  { value: "278", label: "Boğaziçi Üniversitesi" },
  { value: "279", label: "Bozok Üniversitesi" },
  { value: "351", label: "Burdur Mehmet Akif Ersoy Üniversitesi" },
  { value: "417", label: "Bursa Teknik Üniversitesi" },
  { value: "387", label: "Bursa Uludağ Üniversitesi" },
  { value: "282", label: "Çağ Üniversitesi" },
  { value: "283", label: "Çanakkale 18 Mart Üniversitesi" },
  { value: "421", label: "Canik Başarı Üniversitesi" },
  { value: "284", label: "Çankaya Üniversitesi" },
  { value: "285", label: "Çankırı Karatekin Üniversitesi" },
  { value: "286", label: "Çukurova Üniversitesi" },
  { value: "287", label: "Dicle Üniversitesi" },
  { value: "288", label: "Doğu Akdeniz Üniversitesi" },
  { value: "289", label: "Doğuş Üniversitesi" },
  { value: "290", label: "Dokuz Eylül Üniversitesi" },
  { value: "451", label: "Dr. Suat Günsel Girne Üniversitesi" },
  { value: "292", label: "Düzce Üniversitesi" },
  { value: "293", label: "Ege Üniversitesi" },
  { value: "294", label: "Erciyes Üniversitesi" },
  { value: "295", label: "Erzincan Binali Yıldırım Üniversitesi" },
  { value: "422", label: "Erzurum Teknik Üniversitesi" },
  { value: "367", label: "Eskişehir Osmangazi Üniversitesi" },
  { value: "458", label: "Eskişehir Teknik Üniversitesi" },
  { value: "411", label: "Fatih Sultan Mehmet Üniversitesi" },
  { value: "483", label: "Fenerbahçe Üniversitesi" },
  { value: "297", label: "Fırat Üniversitesi" },
  { value: "298", label: "Galatasaray Üniversitesi" },
  { value: "299", label: "Gazi Üniversitesi" },
  { value: "459", label: "Gaziantep İslam Bilim ve Teknoloji Üniversitesi" },
  { value: "300", label: "Gaziantep Üniversitesi" },
  { value: "303", label: "Gebze Teknik Üniversitesi" },
  { value: "305", label: "Giresun Üniversitesi" },
  { value: "306", label: "Girne Amerikan Üniversitesi" },
  { value: "479", label: "Girne Üniversitesi" },
  { value: "307", label: "Gülhane Askeri Tıp Akademisi" },
  { value: "308", label: "Gümüşhane Üniversitesi" },
  { value: "309", label: "Hacettepe Üniversitesi" },
  { value: "310", label: "Hakkari Üniversitesi" },
  { value: "311", label: "Haliç Üniversitesi" },
  { value: "312", label: "Harran Üniversitesi" },
  { value: "301", label: "Hasan Kalyoncu Üniversitesi" },
  { value: "356", label: "Hatay Mustafa Kemal Üniversitesi" },
  { value: "313", label: "Hitit Üniversitesi" },
  { value: "439", label: "İbn Haldun Üniversitesi" },
  { value: "314", label: "Iğdır Üniversitesi" },
  { value: "275", label: "İhsan Doğramacı Bilkent Üniversitesi" },
  { value: "316", label: "İnönü Üniversitesi" },
  { value: "315", label: "Işık Üniversitesi" },
  { value: "430", label: "İskenderun Teknik Üniversitesi" },
  { value: "460", label: "Isparta Uygulamalı Bilimler Üniversitesi" },
  { value: "412", label: "İstanbul 29 Mayıs Üniversitesi" },
  { value: "261", label: "İstanbul Arel Üniversitesi" },
  { value: "462", label: "İstanbul Atlas Üniversitesi" },
  { value: "317", label: "İstanbul Aydın Üniversitesi" },
  { value: "440", label: "İstanbul Ayvansaray Üniversitesi" },
  { value: "318", label: "İstanbul Bilgi Üniversitesi" },
  { value: "319", label: "İstanbul Bilim Üniversitesi" },
  { value: "431", label: "İstanbul Esenyurt Üniversitesi" },
  { value: "487", label: "İstanbul Galata Üniversitesi" },
  { value: "414", label: "İstanbul Gedik Üniversitesi" },
  { value: "320", label: "İstanbul Gelişim Üniversitesi" },
  { value: "321", label: "İstanbul Kavram Üniversitesi" },
  { value: "441", label: "İstanbul Kent Üniversitesi" },
  { value: "323", label: "İstanbul Kültür Üniversitesi" },
  { value: "420", label: "İstanbul Medeniyet Üniversitesi" },
  { value: "405", label: "İstanbul Medikal Üniversitesi" },
  { value: "350", label: "İstanbul Medipol Üniversitesi" },
  { value: "442", label: "İstanbul Rumeli Üniversitesi" },
  { value: "488", label: "İstanbul Sağlık ve Teknoloji Üniversitesi" },
  { value: "415", label: "İstanbul Sebahattin Zaim Üniversitesi" },
  { value: "324", label: "İstanbul Şehir Üniversitesi" },
  { value: "325", label: "İstanbul Teknik Üniversitesi" },
  { value: "326", label: "İstanbul Ticaret Üniversitesi" },
  { value: "486", label: "İstanbul Topkapı Üniversitesi" },
  { value: "327", label: "İstanbul Üniversitesi" },
  { value: "489", label: "İstanbul Üniversitesi - Cerrahpaşa" },
  { value: "394", label: "İstanbul Yeni Yüzyıl Üniversitesi" },
  { value: "443", label: "İstinye Üniversitesi" },
  { value: "444", label: "İzmir Bakırçay Üniversitesi" },
  { value: "445", label: "İzmir Demokrasi Üniversitesi" },
  { value: "328", label: "İzmir Ekonomi Üniversitesi" },
  { value: "402", label: "İzmir Katip Çelebi Üniversitesi" },
  { value: "463", label: "İzmir Tınaztepe Üniversitesi" },
  { value: "329", label: "İzmir Üniversitesi" },
  { value: "330", label: "İzmir Yüksek Teknoloji Enstitüsü" },
  { value: "331", label: "Kadir Has Üniversitesi" },
  { value: "332", label: "Kafkas Üniversitesi" },
  { value: "464", label: "Kahramanmaraş İstiklal Üniversitesi" },
  { value: "333", label: "Kahramanmaraş Sütçü İmam Üniversitesi" },
  { value: "334", label: "Kapadokya Üniversitesi" },
  { value: "335", label: "Karabük Üniversitesi" },
  { value: "336", label: "Karadeniz Teknik Üniversitesi" },
  { value: "337", label: "Karamanoğlu Mehmetbey Üniversitesi" },
  { value: "339", label: "Kastamonu Üniversitesi" },
  { value: "465", label: "Kayseri Üniversitesi" },
  { value: "452", label: "Kıbrıs Ada Kent Üniversitesi" },
  { value: "490", label: "Kıbrıs Amerikan Üniversitesi" },
  { value: "485", label: "Kıbrıs İlim Üniversitesi" },
  { value: "478", label: "Kıbrıs Sosyal Bilimler Üniversitesi" },
  { value: "342", label: "Kilis 7 Aralık Üniversitesi" },
  { value: "340", label: "Kırıkkale Üniversitesi" },
  { value: "341", label: "Kırklareli Üniversitesi" },
  { value: "251", label: "Kırşehir Ahi Evran Üniversitesi" },
  { value: "344", label: "Koç Üniversitesi" },
  { value: "491", label: "Kocaeli Sağlık ve Teknoloji Üniversitesi" },
  { value: "343", label: "Kocaeli Üniversitesi" },
  { value: "446", label: "Konya Gıda ve Tarım Üniversitesi" },
  { value: "466", label: "Konya Teknik Üniversitesi" },
  { value: "338", label: "KTO Karatay Üniversitesi" },
  { value: "291", label: "Kütahya Dumlupınar Üniversitesi" },
  { value: "467", label: "Kütahya Sağlık Bilimleri Üniversitesi" },
  { value: "346", label: "Lefke Avrupa Üniversitesi" },
  { value: "468", label: "Lokman Hekim Üniversitesi" },
  { value: "469", label: "Malatya Turgut Özal Üniversitesi" },
  { value: "347", label: "Maltepe Üniversitesi" },
  { value: "280", label: "Manisa Celal Bayar Üniversitesi" },
  { value: "348", label: "Mardin Artuklu Üniversitesi" },
  { value: "349", label: "Marmara Üniversitesi" },
  { value: "427", label: "MEF Üniversitesi" },
  { value: "353", label: "Mersin Üniversitesi" },
  { value: "404", label: "Mevlana Üniversitesi" },
  { value: "447", label: "Milli Savunma Üniversitesi" },
  { value: "354", label: "Mimar Sinan Güzel Sanatlar Üniversitesi" },
  { value: "355", label: "Muğla Sıtkı Koçman Üniversitesi" },
  { value: "384", label: "Munzur Üniversitesi" },
  { value: "357", label: "Muş Alparslan Üniversitesi" },
  { value: "406", label: "Necmettin Erbakan Üniversitesi" },
  { value: "470", label: "Netkent Akdeniz Araştırma ve Bilim Üniversitesi" },
  { value: "359", label: "Nevşehir Hacı Bektaş Veli Üniversitesi" },
  { value: "360", label: "Niğde Ömer Halisdemir Üniversitesi" },
  { value: "413", label: "Nişantaşı Üniversitesi" },
  { value: "361", label: "Nuh Naci Yazgan Üniversitesi" },
  { value: "362", label: "Okan Üniversitesi" },
  { value: "363", label: "Ondokuz Mayıs Üniversitesi" },
  { value: "364", label: "Ordu Üniversitesi" },
  { value: "418", label: "Orhan Gazi Üniversitesi" },
  { value: "365", label: "Orta Doğu Teknik Üniversitesi" },
  { value: "366", label: "Orta Doğu Teknik Üniversitesi - KIBRIS" },
  { value: "368", label: "Osmaniye Korkut Ata Üniversitesi" },
  { value: "448", label: "Ostim Teknik Üniversitesi" },
  { value: "369", label: "Özyeğin Üniversitesi" },
  { value: "370", label: "Pamukkale Üniversitesi" },
  { value: "371", label: "Piri Reis Üniversitesi" },
  { value: "372", label: "Recep Tayyip Erdoğan Üniversitesi" },
  { value: "373", label: "Sabancı Üniversitesi" },
  { value: "449", label: "Sağlık Bilimleri Üniversitesi" },
  { value: "374", label: "Sakarya Üniversitesi" },
  { value: "471", label: "Sakarya Uygulamalı Bilimler Üniversitesi" },
  { value: "472", label: "Samsun Üniversitesi" },
  { value: "432", label: "Sanko Üniversitesi" },
  { value: "345", label: "Selçuk Üniversitesi" },
  { value: "473", label: "Semerkand Bilim ve Medeniyet Üniversitesi" },
  { value: "403", label: "Şifa Tıp Üniversitesi" },
  { value: "375", label: "Siirt Üniversitesi" },
  { value: "376", label: "Sinop Üniversitesi" },
  { value: "378", label: "Şırnak Üniversitesi" },
  { value: "474", label: "Sivas Bilim ve Teknoloji Üniversitesi" },
  { value: "281", label: "Sivas Cumhuriyet Üniversitesi" },
  { value: "377", label: "Süleyman Demirel Üniversitesi" },
  { value: "409", label: "Süleyman Şah Üniversitesi" },
  { value: "475", label: "Tarsus Üniversitesi" },
  { value: "423", label: "TED Üniversitesi" },
  { value: "358", label: "Tekirdağ Namık Kemal Üniversitesi" },
  { value: "381", label: "TOBB Ekonomi Ve Teknoloji Üniversitesi" },
  { value: "302", label: "Tokat Gaziosmanpaşa Üniversitesi" },
  { value: "382", label: "Toros Üniversitesi" },
  { value: "476", label: "Trabzon Üniversitesi" },
  { value: "383", label: "Trakya Üniversitesi" },
  { value: "424", label: "Türk Alman Üniversitesi" },
  { value: "477", label: "Türkiye Uluslararası İslam, Bilim ve Teknoloji Üniversitesi" },
  { value: "492", label: "Türk-Japon Bilim ve Teknoloji Üniversitesi" },
  { value: "386", label: "Ufuk Üniversitesi" },
  { value: "408", label: "Uluslararası Antalya Üniversitesi" },
  { value: "388", label: "Uluslararası Kıbrıs Üniversitesi" },
  { value: "389", label: "Uşak Üniversitesi" },
  { value: "407", label: "Üsküdar Üniversitesi" },
  { value: "398", label: "Van Yüzüncü Yıl Üniversitesi" },
  { value: "390", label: "Yakın Doğu Üniversitesi" },
  { value: "391", label: "Yalova Üniversitesi" },
  { value: "392", label: "Yaşar Üniversitesi" },
  { value: "393", label: "Yeditepe Üniversitesi" },
  { value: "396", label: "Yıldız Teknik Üniversitesi" },
  { value: "450", label: "Yüksek İhtisas Üniversitesi" },
  { value: "400", label: "Zonguldak Bülent Ecevit Üniversitesi" },
];
